# Generated by Django 4.2.4 on 2023-09-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='Book_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_image',
            new_name='Book_image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='Book_title',
        ),
    ]
